version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: uniswap-stats-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=uniswap_stats
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    networks:
      - uniswap-network
      
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniswap-stats-webapp
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/uniswap_stats?authSource=admin
    depends_on:
      - mongodb
    restart: always
    networks:
      - uniswap-network

networks:
  uniswap-network:
    driver: bridge

volumes:
  mongodb_data:
